### ISSUE TITLE
[Request] Magisk Delta

### ISSUE THREAD

**Issue by jhay06** [pagkly/magiskonwaydroid#12]
Hello for the maintainer,
 
Thank you for your efforts to bring magisk on waydroid. :) 

i'm here for a suggestion if you don't mind.

i found out that there's a magisk delta, (not related on the official magisk but a fork of it)
https://huskydg.github.io/magisk-files/

i tried it , there's an option there that allow emulator to update magisk , but currently it only works on android emulator , 

as per maintainer. it supports zygisk. 

if you can check it and merge some of the source code ? maybe it will help us to use zygisk as well?

thanks

**Comment by ayasa520** [comment]
Can you please install magisk on the official latest A11 image

**Comment by pagkly** [comment]
Hi, have added Magisk Delta canary build. Unfortunately, I currently dont have space for linux machine to test. Hoping somebody can provide testing feedback.
