### ISSUE TITLE
failed to add service

### ISSUE THREAD

**Issue by NewthanGuy** [pagkly/magiskonwaydroid#2]
it fails to add a service and doesnt work

**Comment by pagkly** [comment]
![image](https://user-images.githubusercontent.com/28628331/169456222-ddbf718b-32d4-4fa5-9728-51cc0763d09e.png)
Hey, I just tried running the workflow and it seemed to work fine.
Can you send a screenshot of what error you have? Is it during the workflow or inside waydroid?
If possible, try fetch upstream and try running again.

**Comment by NewthanGuy** [comment]
i fixed the ploblem but waydroid doesn't start
