### ISSUE TITLE
No sound support

### ISSUE THREAD

**Issue by chiyuki0325** [pagkly/magiskonwaydroid#5]
**Distro (If error in Waydroid only)**
Arch

This image has no sound support, any sound played in Android will not be forwarded

**Comment by pagkly** [comment]
Not sure if sound is working since I have not tested playing music/video in Waydroid.
Just to be sure, did you use pipewire?

**Comment by chiyuki0325** [comment]
Yes, I'm using pipewire.The image in README works, but the latest image in Actions doesn't.

**Comment by Genxster1998** [comment]
> Yes, I'm using pipewire.The image in README works, but the latest image in Actions doesn't.

Which image does work ?
